### ISSUE TITLE
`model.named_modules` returns PyTorch modules not NNSight wrapped modules

### ISSUE THREAD

**Issue by neelnanda-io** [ndif-team/nnsight#114]
I want to iterate over all submodules of an NNSight model using `for name, module in model.named_modules()` inside a trace context. But when I do this, the returned modules are just PyTorch modules, and don't have NNSight attributes like `input` and `output`

Motivation: I was trying to implement an equivalent of TransformerLens' `run_with_cache`, where we can run a model on some input and cache all intermediate activations. The key difficulty I ran into was iterating over _all_ submodules to access their outputs (it's easy to do this if you know the model architecture and can enumerate them, but annoying and fiddly, and doesn't generalise between models).

Example:

```
from nnsight import LanguageModel

model = LanguageModel("openai-community/gpt2", device_map="auto")

with model.trace("The Eiffel Tower is in the city of"):
    cache = {}
    for name, mod in model.named_modules():
        print(name)
        print(type(mod))
        cache[name] = mod.output.save()
```

The type of the module is the expected PyTorch layer type, not an NNSight `Envoy` object, and this gives the following error as `mod` does not have an `output` attribute

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-1798760a759f> in <cell line: 1>()
----> 1 with model.trace("The Eiffel Tower is in the city of"):
      2     cache = {}
      3     for name, mod in model.named_modules():
      4         # print(name)
      5         # print(type(mod))

2 frames
/usr/local/lib/python3.10/dist-packages/nnsight/contexts/Runner.py in __exit__(self, exc_type, exc_val, exc_tb)
     39         """On exit, run and generate using the model whether locally or on the server."""
     40         if isinstance(exc_val, BaseException):
---> 41             raise exc_val
     42 
     43         if self.remote:

<ipython-input-25-1798760a759f> in <cell line: 1>()
      4         # print(name)
      5         # print(type(mod))
----> 6         cache[name] = mod.output.save()

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1686             if name in modules:
   1687                 return modules[name]
-> 1688         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1689 
   1690     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'GPT2LMHeadModel' object has no attribute 'output'
```

**Comment by JadenFiotto-Kaufman** [comment]
@neelnanda-io I actually just added something that work work here with Envoy.envoys() (or model.envoys()) 

https://github.com/ndif-team/nnsight/blob/12db3b599fc2224cb66c74d78844d40efeaf3d4f/src/nnsight/envoy.py#L210

For your case it would look like:

```python
from nnsight import LanguageModel

model = LanguageModel("openai-community/gpt2", device_map="auto")

with model.trace("The Eiffel Tower is in the city of"):
    cache = {}
    for envoy in model.envoys():
        print(envoy._module_path)
        print(type(envoy._module))
        cache[name] = envoy.output.save()
```
You can also pass a fn in to .envoys() to include only some with a condition.

Maybe I should just assume people want to use an NNSight model as close as possible to a normal pytorch model and rename .envoys() to .modules() and also add .named_modules(). What are your thoughts on that?

**Comment by neelnanda-io** [comment]
Oh, awesome, that works great! Thank you. There's some complications to getting it to work properly (eg `model.transformer.h` has output a list, so `.save()` doesn't work on it), but wrapping that in a try, except works fine. 

Yes, I think that trying to be as close as possible to the existing library is great, to minimise the need to learn new syntax. You really want new users to be able to zero shot guess the right way to do things without needing to read docs (especially if they might otherwise not even realise the feature exists/not know where to look, like me!). Converting it to `.modules` and adding `named_modules` as a wrapper that also returns `envoy._module_path` seems like a great idea

I'm surprised that the types of the objects in the cache are `nnsight.models.LanguageModel.LanguageModelProxy` not tensors or tuples, why does that happen? It's outside a trace statement

**Comment by neelnanda-io** [comment]
I think having a function like `model.run_with_cache(*args, **kwargs)` that returns the above cache might be a generally useful util, fwiw, it's one of my most commonly used TransformerLens functions, and it'd be great for NNSight to make it easy to do this on any HuggingFace model!

**Comment by JadenFiotto-Kaufman** [comment]
> Oh, awesome, that works great! Thank you. There's some complications to getting it to work properly (eg `model.transformer.h` has output a list, so `.save()` doesn't work on it), but wrapping that in a try, except works fine.

Ah okay makes sense. I should probably have a way for .output on a ModuleList returns a Proxy and is therefore saveable.

> Yes, I think that trying to be as close as possible to the existing library is great, to minimise the need to learn new syntax. You really want new users to be able to zero shot guess the right way to do things without needing to read docs (especially if they might otherwise not even realise the feature exists/not know where to look, like me!). Converting it to `.modules` and adding `named_modules` as a wrapper that also returns `envoy._module_path` seems like a great idea

Okay yeah awesome makes sense!

> I'm surprised that the types of the objects in the cache are `nnsight.models.LanguageModel.LanguageModelProxy` not tensors or tuples, why does that happen? It's outside a trace statement

So how nnsight works is the variables you create in the .trace (like module.input/output and the operations on those) are Proxies for an eventual output. When you exit the `with .trace()` block, the model is actually ran with all of the operations/interventions you defined in the .trace() context. When the output or input of a module is actually calculated, its injected into the Proxy, which cascades to all Proxies that rely on it (dependencies), so on and so forth. Proxies also track other Proxies that depend on it (listeners) and if all of its listeners are done, it assumes its no longer needed and deletes its value. Calling .save() on a Proxy prevents this. This value can be accessed by doing `Proxy.value` (youll get an error if it was never populated. So once you exit the `with .trace()` block, you can call .value on the Proxy objects to get the true value (tensor or whatever).

Often in practice though, you don't actually need to call .value on Proxies outside the tracing context as nnsight knows whether or not its in the tracing context. So if outside it, all operations on Proxies just return the underlying value. This includes printing. Example:

```python
from nnsight import LanguageModel

model = LanguageModel("openai-community/gpt2", device_map="auto")

with model.trace("The Eiffel Tower is in the city of"):
    proxy = model.output.save()
    print(proxy) # This prints out a Proxy with some information about what the eventual value might look like
    print(type(proxy)) # This prints that its a proxy
    
print(proxy) # This will print out the true underlying .value, even though its still a Proxy
print(type(proxy)) # Still a Proxy

value = proxy.value # value is now the underlying tensor or whatever

sum = proxy.sum() # Calling an operation on a Proxy outside of the tracing context does actually create a new Proxy, however it knows to immediately execute and return the underlying .value instead of the Proxy.

print(type(sum)) # This is a tensor
```
