### ISSUE TITLE
Make it easier to see what default inputs can go in `LanguageModel`

### ISSUE THREAD

**Issue by loftusa** [ndif-team/nnsight#173]
`model = LanguageModel("gpt2")`

The `help` for `LanguageModel` doesn't say which other models are in the default namespace (for instance, can I do "llama3"? "gemma2"? etc). It would be nice to see a list somewhere.

This is especially helpful for knowing which models we can pass `remote=True` for

**Comment by ericwtodd** [comment]
To your second point, you can see which models are currently hosted on the nnsight website: https://nnsight.net/status/

**Comment by JadenFiotto-Kaufman** [comment]
@loftusa Do you mean remotely or just in general? The string like "openai-community/gpt2" is a huggingface repo id so whatever  they support we support. You kinda just have to google what models are on huggingface.
