### ISSUE TITLE
Padding behavior when using a remote vs. local runner

### ISSUE THREAD

**Issue by HelenaCasademunt** [ndif-team/nnsight#234]
When multiple invokes are used inside a single trace, the inputs are batched and padded as needed. When this is done locally, it looks like the default tokenizer behavior is used. However, something else happens when using the remote server. For example, running the following snippet shows that left padding is used locally but right padding is used remotely.
```
model = LanguageModel('EleutherAI/gpt-j-6b', device_map='auto')
for remote in [True, False]:
    with model.trace(remote=remote) as runner:
        with runner.invoke(["fish are friends, not food"]):
            pass
        with runner.invoke(["fish are friends"]):
            tokens = model.transformer.input.save()
    print(tokens)
```

**Comment by JadenFiotto-Kaufman** [comment]
@HelenaCasademunt Okay yeah heres what happened. In 0.3 I decided I wasn't going to force padding side left anymore and after talking to some people decided that was a bad idea and what patched to now default to left but not enforce. The environment the gptj model node was running on was using the pre-patched nnsight. I just restarted everything and tested the code in the issue which now returns the same tokens both times. Sorry about that
