### ISSUE TITLE
Feature Request: add `input_kw` to capture inputs passed as kwargs in module/submodules 

### ISSUE THREAD

**Issue by arnab-api** [ndif-team/nnsight#277]
Often arguments are passed as kwargs, see [**this**](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L545)

Does `nnsight` already has a feature to capture such inputs? I couldn't figure it out. If not, is it possible to add a `input_kw` attribute in the module specific hooks to capture them? 

```
with torch.inference_mode():
    with lm.trace(
        prompts,
        **tracer_args,
        invoker_args
    ) as tr:
        submodule_input = lm.submodule.input.save() # <-- save inputs passed as args
        submodule_input_kw = lm.submodule.input_kw.save() # <-- save inputs passed as kwargs

submodule_input_kw.causal_mask  # <-- accessing specific kwarg input
```

Not sure if you will find this relevant: I created [**this pull request for `baukit`**](https://github.com/davidbau/baukit/pull/2) to add this feature a while ago. The main channel of `baukit` still doesn't have this feature, btw. But I have been using my version (with the pull request) for some time. Still haven't faced any issue.

**Comment by AdamBelfki3** [comment]
If you call `lm.submodule.inputs` in `nnsight`, it should give you the full submodule input with both the positional arguments (which includes the input values) and the keyword arguments. Then you can just index for the kwargs by doing `lm.submodule.inputs[1]`.

Can you try this and let me know if it doesn't achieve what you are looking for.

**Comment by arnab-api** [comment]
`inputs` solves this.
Thanks!
