### ISSUE TITLE
[Feature request]: Generalized submodule accessor

### ISSUE THREAD

**Issue by t-shoemaker** [ndif-team/nnsight#303]
This framework is extremely promising, and I'm keen to see it develop! As you work toward v1.0, I'd like to suggest some kind of functionality that enables users to access submodule components without hard-coding. It seems to me that flexible, scaled model comparisons will require some standardized mode of access that generalizes beyond attribute accessors (I recognize this is partly a limitation of PyTorch).

For example, instead of:

```py
from nnsight import LanguageModel
model = LanguageModel('gpt2', device_map='cuda:0')

with model.trace("Some sequence of text"):
    output = model.transformer.h[5].mlp.output.save()
```

Using something like stringified submodule accessors:

```py
with model.trace("Some sequence of text"):
    output = model.get("transformer.h.5.mlp.output").save()
```

...would mean a particular Python script could work for multiple different models and layer types using external configuration in, say, a TOML file or the like. Unless I'm missing something, as things currently stand I have to rely on an external function to achieve this (which is fine but perhaps not ideal):

```py
def get_submodule(
    model: LanguageModel, submodule_name: str, sep: str = "."
) -> Envoy:
    """Get a submodule from the LanguageModel.

    Submodule names are in the format <module><sep><module>...

    Parameters
    ----------
    model : LanguageModel
        The model
    submodule_name : str
        Stringified name of the submodule
    sep : str
        Separator character for submodule components

    Returns
    -------
    Envoy
        The submodule

    Raises
    ------
    AttributeError
        If the model does not have a requested submodule component
    """
    modules = submodule_name.split(sep)
    submodule = model
    while len(modules) > 0:
        module, *_ = modules
        if not hasattr(submodule, module):
            raise AttributeError(
                f"Couldn't access module '{module}' for {submodule_name}"
            )

        submodule = getattr(submodule, module)
        modules.pop(0)

    return submodule
```

**Comment by JadenFiotto-Kaufman** [comment]
@t-shoemaker  Good idea! Done https://github.com/ndif-team/nnsight/pull/305

**Comment by t-shoemaker** [comment]
Great, thanks!
